### ISSUE TITLE
Bug conversione MM-CooMatrix

### ISSUE THREAD

**Issue by lucaFiscariello** [scpa-2023/matrix-multiVector-product#21]
Durante la conversione la matrice in formato MM non legge correttamente dal file. I primi valori vengono letti correttamente , arrivati poi al secondo non zero si ottiene "nonZero in position 2 =  riga:-1 colonna: 15706959 valore: 0.000000".  Questo errore si presenta con la matrice "trec5".  Il fatto di avere un indice pari a -1 fa sollevare una segmentation fault in qualche zona del codice.

Per testare questo errore mandare in esecuzione il test "testProduct()" nel file main.

**Comment by Torkin1** [comment]
Sembra che ciò sia correlato alle invocazioni di `appendLL()` dentro il metodo `putCOO`. Sostuire le liste collegate con degli array riallocati dinamicamente quando necessario potrebbe risolvere il problema.

**Comment by Torkin1** [comment]
fixed in 62da7a6fc63894860bbbbd329029f4a6e5f8c326
